name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using the latest Ubuntu environment for the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from GitHub

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Setting PHP version to 8.3

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist  # Install Laravel dependencies
          npm install  # If you're using NPM for frontend dependencies
          npm run prod  # Run production build for assets (optional)

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: latest

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up --name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RG }} --location ${{ secrets.AZURE_REGION }} --sku F1 --runtime "PHP|8.3" --src-path .

      - name: Azure Deployment complete
        run: echo "Deployment to Azure is complete!"
