name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm install
          npx vite@latest build

      - name: Set up environment variables
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.AZURE_DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.AZURE_DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.AZURE_DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.AZURE_DB_PASSWORD }}" >> .env
          php artisan config:cache

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: latest

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up --name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RG }} --location ${{ secrets.AZURE_REGION }} --sku F1 --runtime "PHP|8.3" --src-path .

      - name: Run database migrations
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Azure Deployment complete
        run: echo "Deployment to Azure is complete!"
